name: publish_live

on:
    # Automatic publishing on push
    push:
        branches:
            - main
    # Manually triggered publish
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-22.04
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - run: pip install mkdocs-material mkdocs-glightbox
        - run: mkdocs build

        # Publish to the preview pages
        - name: Publish to Cloudflare Pages
          uses: cloudflare/pages-action@v1
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            projectName: oq-website
            directory: site
